# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST https://www.dxmaps.com/dxcalendar.php
Content-Type: application/x-www-form-urlencoded

View=30DAY&DXCC=0&IOTA=&CQ=ALL&Mode=ALL&Band=HF
