namespace AF0E.DB.Models;

public sealed class HrdLog
{
    public int ColPrimaryKey { get; init; }
    public string? ColAddress { get; init; }
    public double? ColAge { get; init; }
    public double? ColAIndex { get; init; }
    public double? ColAntAz { get; init; }
    public double? ColAntEl { get; init; }
    public string? ColAntPath { get; init; }
    public string? ColArrlSect { get; init; }
    public string? ColBand { get; init; }
    public string? ColBandRx { get; init; }
    public string? ColBiography { get; init; }
    public string ColCall { get; init; } = null!;
    public string? ColCheck { get; init; }
    public string? ColClass { get; init; }
    public string? ColCnty { get; init; }
    public string? ColComment { get; set; }
    public string? ColCont { get; init; }
    public string? ColContactedOp { get; init; }
    public string? ColContestId { get; init; }
    public string? ColCountry { get; init; }
    public double? ColCqz { get; init; }
    public double? ColDistance { get; init; }
    public string? ColDxcc { get; init; }
    public string? ColEmail { get; init; }
    public string? ColEqCall { get; init; }
    public DateTime? ColEqslQslrdate { get; init; }
    public DateTime? ColEqslQslsdate { get; init; }
    public string? ColEqslQslRcvd { get; init; }
    public string? ColEqslQslSent { get; init; }
    public string? ColEqslStatus { get; init; }
    public double? ColForceInit { get; init; }
    public double? ColFreq { get; init; }
    public double? ColFreqRx { get; init; }
    public string? ColGridsquare { get; init; }
    public double? ColHeading { get; init; }
    public string? ColIota { get; init; }
    public double? ColItuz { get; init; }
    public double? ColKIndex { get; init; }
    public double? ColLat { get; init; }
    public double? ColLon { get; init; }
    public DateTime? ColLotwQslrdate { get; init; }
    public DateTime? ColLotwQslsdate { get; init; }
    public string? ColLotwQslRcvd { get; init; }
    public string? ColLotwQslSent { get; init; }
    public string? ColLotwStatus { get; init; }
    public double? ColMaxBursts { get; init; }
    public string? ColMode { get; init; }
    public string? ColMsShower { get; init; }
    public string? ColMyCity { get; init; }
    public string? ColMyCnty { get; init; }
    public string? ColMyCountry { get; init; }
    public double? ColMyCqZone { get; init; }
    public string? ColMyGridsquare { get; init; }
    public string? ColMyIota { get; init; }
    public double? ColMyItuZone { get; init; }
    public double? ColMyLat { get; init; }
    public double? ColMyLon { get; init; }
    public string? ColMyName { get; init; }
    public string? ColMyPostalCode { get; init; }
    public string? ColMyRig { get; init; }
    public string? ColMySig { get; init; }
    public string? ColMySigInfo { get; init; }
    public string? ColMyState { get; init; }
    public string? ColMyStreet { get; init; }
    public string? ColName { get; init; }
    public string? ColNotes { get; init; }
    public double? ColNrBursts { get; init; }
    public double? ColNrPings { get; init; }
    public string? ColOperator { get; init; }
    public string? ColOwnerCallsign { get; init; }
    public string? ColPfx { get; init; }
    public string? ColPrecedence { get; init; }
    public string? ColPropMode { get; init; }
    public string? ColPublicKey { get; init; }
    public string? ColQslmsg { get; init; }
    public DateTime? ColQslrdate { get; init; }
    public DateTime? ColQslsdate { get; set; }
    public string? ColQslRcvd { get; init; }
    public string? ColQslRcvdVia { get; init; }
    public string? ColQslSent { get; set; }
    public string? ColQslSentVia { get; set; }
    public string? ColQslVia { get; set; }
    public string? ColQsoComplete { get; init; }
    public double? ColQsoRandom { get; init; }
    public string? ColQth { get; init; }
    public string? ColRig { get; init; }
    public string? ColRstRcvd { get; init; }
    public string? ColRstSent { get; init; }
    public double? ColRxPwr { get; init; }
    public string? ColSatMode { get; init; }
    public string? ColSatName { get; init; }
    public double? ColSfi { get; init; }
    public string? ColSig { get; init; }
    public string? ColSigInfo { get; init; }
    public double? ColSrx { get; init; }
    public string? ColSrxString { get; init; }
    public string? ColState { get; init; }
    public string? ColStationCallsign { get; init; }
    public double? ColStx { get; init; }
    public string? ColStxString { get; init; }
    public double? ColSwl { get; init; }
    public double? ColTenTen { get; init; }
    public DateTime? ColTimeOff { get; init; }
    public DateTime? ColTimeOn { get; init; }
    public double? ColTxPwr { get; init; }
    public string? ColWeb { get; init; }
    public string? SiteComment { get; set; }
    public string? QslMgrCall { get; set; }
    public string? QslComment { get; set; }
    public string? Metadata { get; set; }
    public string? ColUserDefined4 { get; init; }
    public string? ColUserDefined5 { get; init; }
    public string? ColUserDefined6 { get; init; }
    public string? ColUserDefined7 { get; init; }
    public string? ColUserDefined8 { get; init; }
    public string? ColUserDefined9 { get; init; }
    public string? ColCreditGranted { get; init; }
    public string? ColCreditSubmitted { get; init; }
    public string? ColIsmultiplier { get; init; }
    public string? ColRoverlocation { get; init; }
    public string? ColHrdcountryno { get; init; }
    public string? ColSubmode { get; init; }

    public ICollection<PotaContact> PotaContacts { get; init; } = [];
}
