namespace AF0E.DB.Models;

public sealed class HrdLog
{
    public int ColPrimaryKey { get; set; }
    public string? ColAddress { get; set; }
    public double? ColAge { get; set; }
    public double? ColAIndex { get; set; }
    public double? ColAntAz { get; set; }
    public double? ColAntEl { get; set; }
    public string? ColAntPath { get; set; }
    public string? ColArrlSect { get; set; }
    public string? ColBand { get; set; }
    public string? ColBandRx { get; set; }
    public string? ColBiography { get; set; }
    public string ColCall { get; set; } = null!;
    public string? ColCheck { get; set; }
    public string? ColClass { get; set; }
    public string? ColCnty { get; set; }
    public string? ColComment { get; set; }
    public string? ColCont { get; set; }
    public string? ColContactedOp { get; set; }
    public string? ColContestId { get; set; }
    public string? ColCountry { get; set; }
    public double? ColCqz { get; set; }
    public double? ColDistance { get; set; }
    public string? ColDxcc { get; set; }
    public string? ColEmail { get; set; }
    public string? ColEqCall { get; set; }
    public DateTime? ColEqslQslrdate { get; set; }
    public DateTime? ColEqslQslsdate { get; set; }
    public string? ColEqslQslRcvd { get; set; }
    public string? ColEqslQslSent { get; set; }
    public string? ColEqslStatus { get; set; }
    public double? ColForceInit { get; set; }
    public double? ColFreq { get; set; }
    public double? ColFreqRx { get; set; }
    public string? ColGridsquare { get; set; }
    public double? ColHeading { get; set; }
    public string? ColIota { get; set; }
    public double? ColItuz { get; set; }
    public double? ColKIndex { get; set; }
    public double? ColLat { get; set; }
    public double? ColLon { get; set; }
    public DateTime? ColLotwQslrdate { get; set; }
    public DateTime? ColLotwQslsdate { get; set; }
    public string? ColLotwQslRcvd { get; set; }
    public string? ColLotwQslSent { get; set; }
    public string? ColLotwStatus { get; set; }
    public double? ColMaxBursts { get; set; }
    public string? ColMode { get; set; }
    public string? ColMsShower { get; set; }
    public string? ColMyCity { get; set; }
    public string? ColMyCnty { get; set; }
    public string? ColMyCountry { get; set; }
    public double? ColMyCqZone { get; set; }
    public string? ColMyGridsquare { get; set; }
    public string? ColMyIota { get; set; }
    public double? ColMyItuZone { get; set; }
    public double? ColMyLat { get; set; }
    public double? ColMyLon { get; set; }
    public string? ColMyName { get; set; }
    public string? ColMyPostalCode { get; set; }
    public string? ColMyRig { get; set; }
    public string? ColMySig { get; set; }
    public string? ColMySigInfo { get; set; }
    public string? ColMyState { get; set; }
    public string? ColMyStreet { get; set; }
    public string? ColName { get; set; }
    public string? ColNotes { get; set; }
    public double? ColNrBursts { get; set; }
    public double? ColNrPings { get; set; }
    public string? ColOperator { get; set; }
    public string? ColOwnerCallsign { get; set; }
    public string? ColPfx { get; set; }
    public string? ColPrecedence { get; set; }
    public string? ColPropMode { get; set; }
    public string? ColPublicKey { get; set; }
    public string? ColQslmsg { get; set; }
    public DateTime? ColQslrdate { get; set; }
    public DateTime? ColQslsdate { get; set; }
    public string? ColQslRcvd { get; set; }
    public string? ColQslRcvdVia { get; set; }
    public string? ColQslSent { get; set; }
    public string? ColQslSentVia { get; set; }
    public string? ColQslVia { get; set; }
    public string? ColQsoComplete { get; set; }
    public double? ColQsoRandom { get; set; }
    public string? ColQth { get; set; }
    public string? ColRig { get; set; }
    public string? ColRstRcvd { get; set; }
    public string? ColRstSent { get; set; }
    public double? ColRxPwr { get; set; }
    public string? ColSatMode { get; set; }
    public string? ColSatName { get; set; }
    public double? ColSfi { get; set; }
    public string? ColSig { get; set; }
    public string? ColSigInfo { get; set; }
    public double? ColSrx { get; set; }
    public string? ColSrxString { get; set; }
    public string? ColState { get; set; }
    public string? ColStationCallsign { get; set; }
    public double? ColStx { get; set; }
    public string? ColStxString { get; set; }
    public double? ColSwl { get; set; }
    public double? ColTenTen { get; set; }
    public DateTime? ColTimeOff { get; set; }
    public DateTime? ColTimeOn { get; set; }
    public double? ColTxPwr { get; set; }
    public string? ColWeb { get; set; }
    public string? SiteComment { get; set; }
    public string? QslMgrCall { get; set; }
    public string? QslComment { get; set; }
    public string? Metadata { get; set; }
    public string? ColUserDefined4 { get; set; }
    public string? ColUserDefined5 { get; set; }
    public string? ColUserDefined6 { get; set; }
    public string? ColUserDefined7 { get; set; }
    public string? ColUserDefined8 { get; set; }
    public string? ColUserDefined9 { get; set; }
    public string? ColCreditGranted { get; set; }
    public string? ColCreditSubmitted { get; set; }
    public string? ColIsmultiplier { get; set; }
    public string? ColRoverlocation { get; set; }
    public string? ColHrdcountryno { get; set; }
    public string? ColSubmode { get; set; }

    public ICollection<PotaContact> PotaContacts { get; set; } = [];
    public ICollection<PotaHunting> PotaHunting { get; set; } = [];
}
