# For more info on HTTP files go to https://aka.ms/vs/httpfile

// DXMaps.com
POST https://www.dxmaps.com/dxcalendar.php
Content-Type: application/x-www-form-urlencoded

View=30DAY&DXCC=0&IOTA=&CQ=ALL&Mode=ALL&Band=HF

###

// DX Scraper Starter
GET https://af0e-functions-dev.azurewebsites.net/api/DxScraperHttpStarter?code={{DXScraperHttpStarterKey}}
